/*
  TSIP run archive — Phase 1 Layer 2 (working-table + STATSUM snapshots).
  Column layouts mirror TabDef.cs TT_* / TE_* working tables and TpReport STATSUM staging.
*/
SET NOCOUNT ON;

IF OBJECT_ID(N'web.tsip_arc_ts_site', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_ts_site (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        interferer     CHAR(1)    NULL,
        intcall1       CHAR(9)    NULL,
        intcall2       CHAR(9)    NULL,
        viccall1       CHAR(9)    NULL,
        viccall2       CHAR(9)    NULL,
        caseno         INT        NULL,
        subcases       INT        NULL,
        intname1       CHAR(32)   NULL,
        intname2       CHAR(32)   NULL,
        vicname1       CHAR(32)   NULL,
        vicname2       CHAR(32)   NULL,
        intoper        CHAR(6)    NULL,
        intoper2       CHAR(6)    NULL,
        vicoper        CHAR(6)    NULL,
        vicoper2       CHAR(6)    NULL,
        intlatit       INT        NULL,
        intlongit      INT        NULL,
        intgrnd        FLOAT      NULL,
        viclatit       INT        NULL,
        viclongit      INT        NULL,
        vicgrnd        FLOAT      NULL,
        report         SMALLINT   NULL,
        int1int2dist   FLOAT      NULL,
        vic1vic2dist   FLOAT      NULL,
        int1vic1dist   FLOAT      NULL,
        distadv        FLOAT      NULL,
        intoffax       FLOAT      NULL,
        vicoffax       FLOAT      NULL,
        intvicaz       FLOAT      NULL,
        vicintaz       FLOAT      NULL,
        processed      INT        NULL,
        CONSTRAINT PK_tsip_arc_ts_site PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_ts_site_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_ts_site_run ON web.tsip_arc_ts_site (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_ts_ante', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_ts_ante (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        interferer     CHAR(1)    NULL,
        intcall1       CHAR(9)    NULL,
        intcall2       CHAR(9)    NULL,
        intbndcde      CHAR(4)    NULL,
        intanum        SMALLINT   NULL,
        viccall1       CHAR(9)    NULL,
        viccall2       CHAR(9)    NULL,
        vicbndcde      CHAR(4)    NULL,
        caseno         INT        NULL,
        vicanum        SMALLINT   NULL,
        intacode       CHAR(12)   NULL,
        vicacode       CHAR(12)   NULL,
        report         SMALLINT   NULL,
        subcaseno      INT        NULL,
        adiscctxh      FLOAT      NULL,
        adiscctxv      FLOAT      NULL,
        adisccrxh      FLOAT      NULL,
        adisccrxv      FLOAT      NULL,
        adiscxtxh      FLOAT      NULL,
        adiscxtxv      FLOAT      NULL,
        adiscxrxh      FLOAT      NULL,
        adiscxrxv      FLOAT      NULL,
        processed      INT        NULL,
        intause        CHAR(4)    NULL,
        vicause        CHAR(4)    NULL,
        intoffaxa      FLOAT      NULL,
        vicoffaxa      FLOAT      NULL,
        intgain        FLOAT      NULL,
        vicgain        FLOAT      NULL,
        intaxref       CHAR(12)   NULL,
        intamodel      CHAR(16)   NULL,
        vicaxref       CHAR(12)   NULL,
        vicamodel      CHAR(16)   NULL,
        intaoffax      CHAR(1)    NULL,
        inthopaz       FLOAT      NULL,
        intantaz       FLOAT      NULL,
        intoffantax    FLOAT      NULL,
        vicaoffax      CHAR(1)    NULL,
        vichopaz       FLOAT      NULL,
        vicantaz       FLOAT      NULL,
        vicoffantax    FLOAT      NULL,
        intaht         FLOAT      NULL,
        vicaht         FLOAT      NULL,
        intvicel       FLOAT      NULL,
        vicintel       FLOAT      NULL,
        intelev        FLOAT      NULL,
        vicelev        FLOAT      NULL,
        CONSTRAINT PK_tsip_arc_ts_ante PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_ts_ante_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_ts_ante_run ON web.tsip_arc_ts_ante (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_ts_chan', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_ts_chan (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        interferer     CHAR(1)    NULL,
        intcall1       CHAR(9)    NULL,
        intcall2       CHAR(9)    NULL,
        intbndcde      CHAR(4)    NULL,
        intanum        SMALLINT   NULL,
        intchid        CHAR(4)    NULL,
        viccall1       CHAR(9)    NULL,
        viccall2       CHAR(9)    NULL,
        vicbndcde      CHAR(4)    NULL,
        vicanum        SMALLINT   NULL,
        caseno         INT        NULL,
        vicchid        CHAR(4)    NULL,
        intpolar       CHAR(1)    NULL,
        vicpolar       CHAR(1)    NULL,
        intstattx      CHAR(1)    NULL,
        vicstatrx      CHAR(1)    NULL,
        inttraftx      CHAR(6)    NULL,
        victrafrx      CHAR(6)    NULL,
        inteqpttx      CHAR(8)    NULL,
        viceqptrx      CHAR(8)    NULL,
        intfreqtx      FLOAT      NULL,
        vicfreqrx      FLOAT      NULL,
        vicpwrrx       FLOAT      NULL,
        intpwrtx       FLOAT      NULL,
        intafsltx      FLOAT      NULL,
        vicafslrx      FLOAT      NULL,
        rxant          SMALLINT   NULL,
        txant          SMALLINT   NULL,
        ctxinttraftx   CHAR(6)    NULL,
        ctxvictrafrx   CHAR(6)    NULL,
        ctxeqpt        CHAR(8)    NULL,
        calctype       CHAR(3)    NULL,
        report         SMALLINT   NULL,
        totantdisc     FLOAT      NULL,
        freqsep        FLOAT      NULL,
        reqdcalc       FLOAT      NULL,
        patloss        FLOAT      NULL,
        calcico        FLOAT      NULL,
        calcixp        FLOAT      NULL,
        resti          FLOAT      NULL,
        eirpadv        FLOAT      NULL,
        tiltdisc       FLOAT      NULL,
        pathloss80     FLOAT      NULL,
        calcico80      FLOAT      NULL,
        calcixp80      FLOAT      NULL,
        reqd80         FLOAT      NULL,
        resti80        FLOAT      NULL,
        pathloss99     FLOAT      NULL,
        calcico99      FLOAT      NULL,
        calcixp99      FLOAT      NULL,
        reqd99         FLOAT      NULL,
        resti99        FLOAT      NULL,
        ohresult       SMALLINT   NULL,
        rqco           FLOAT      NULL,
        processed      INT        NULL,
        ctxinteqpt     CHAR(8)    NULL,
        inteqtype      CHAR(1)    NULL,
        viceqtype      CHAR(1)    NULL,
        intbwchans     FLOAT      NULL,
        vicbwchans     FLOAT      NULL,
        CONSTRAINT PK_tsip_arc_ts_chan PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_ts_chan_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_ts_chan_run ON web.tsip_arc_ts_chan (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_ts_parm', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_ts_parm (
        arc_id      BIGINT     IDENTITY(1,1) NOT NULL,
        run_id      BIGINT     NOT NULL,
        protype     CHAR(1)    NULL,
        envtype     CHAR(8)    NULL,
        proname     CHAR(16)   NULL,
        envname     CHAR(16)   NULL,
        tsorbout    CHAR(1)    NULL,
        spherecalc  CHAR(1)    NULL,
        fsep        FLOAT      NULL,
        coordist    FLOAT      NULL,
        analopt     CHAR(4)    NULL,
        margin      FLOAT      NULL,
        numchan     SMALLINT   NULL,
        chancodes   CHAR(19)   NULL,
        tempant     CHAR(15)   NULL,
        tempctx     CHAR(15)   NULL,
        tempplan    CHAR(15)   NULL,
        tempequip   CHAR(15)   NULL,
        country     CHAR(3)    NULL,
        selsites    CHAR(15)   NULL,
        numcodes    SMALLINT   NULL,
        codes       CHAR(164)  NULL,
        runname     CHAR(5)    NULL,
        reports     INT        NULL,
        numcases    INT        NULL,
        numtecases  INT        NULL,
        parmparm    CHAR(50)   NULL,
        mdate       CHAR(10)   NULL,
        mtime       CHAR(8)    NULL,
        CONSTRAINT PK_tsip_arc_ts_parm PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_ts_parm_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_ts_parm_run ON web.tsip_arc_ts_parm (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_te_site', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_te_site (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        terrcall1      CHAR(9)    NULL,
        terrcall2      CHAR(9)    NULL,
        earthlocation  CHAR(10)   NULL,
        terrname1      CHAR(32)   NULL,
        terrname2      CHAR(32)   NULL,
        earthname      CHAR(16)   NULL,
        terroper       CHAR(6)    NULL,
        terroper2      CHAR(6)    NULL,
        earthoper      CHAR(6)    NULL,
        terrlatit      INT        NULL,
        terrlongit     INT        NULL,
        terrgrnd       FLOAT      NULL,
        earthlatit     INT        NULL,
        earthlongit    INT        NULL,
        earthgrnd      FLOAT      NULL,
        radiozone      CHAR(2)    NULL,
        rainzone       SMALLINT   NULL,
        etreport       SMALLINT   NULL,
        tereport       SMALLINT   NULL,
        etcaseno       INT        NULL,
        tecaseno       INT        NULL,
        etsubcases     INT        NULL,
        tesubcases     INT        NULL,
        intreq         CHAR(4)    NULL,
        etdist         FLOAT      NULL,
        etazim         FLOAT      NULL,
        teazim         FLOAT      NULL,
        tudist         FLOAT      NULL,
        tuazim         FLOAT      NULL,
        utazim         FLOAT      NULL,
        eudist         FLOAT      NULL,
        euazim         FLOAT      NULL,
        ueazim         FLOAT      NULL,
        processed      INT        NULL,
        CONSTRAINT PK_tsip_arc_te_site PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_te_site_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_te_site_run ON web.tsip_arc_te_site (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_te_ante', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_te_ante (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        interferer     CHAR(1)    NULL,
        terrcall1      CHAR(9)    NULL,
        terrcall2      CHAR(9)    NULL,
        terrbndcde     CHAR(4)    NULL,
        terranum       SMALLINT   NULL,
        earthlocation  CHAR(10)   NULL,
        earthcall1     CHAR(9)    NULL,
        earthband      CHAR(4)    NULL,
        terracode      CHAR(12)   NULL,
        earthacode     CHAR(12)   NULL,
        satname        CHAR(16)   NULL,
        satoper        CHAR(3)    NULL,
        satlongit      INT        NULL,
        txpre          FLOAT      NULL,
        txtro          FLOAT      NULL,
        rxpre          FLOAT      NULL,
        rxtro          FLOAT      NULL,
        sarc1          FLOAT      NULL,
        sarc2          FLOAT      NULL,
        mode1          SMALLINT   NULL,
        mode2          SMALLINT   NULL,
        intause        CHAR(4)    NULL,
        etreport       SMALLINT   NULL,
        tereport       SMALLINT   NULL,
        etsubcaseno    INT        NULL,
        tesubcaseno    INT        NULL,
        esazim         FLOAT      NULL,
        eselev         FLOAT      NULL,
        teelev         FLOAT      NULL,
        etelev         FLOAT      NULL,
        tuelev         FLOAT      NULL,
        utelev         FLOAT      NULL,
        euelev         FLOAT      NULL,
        ediscang       FLOAT      NULL,
        tdiscang       FLOAT      NULL,
        adisc_set      FLOAT      NULL,
        adisc_ute      FLOAT      NULL,
        terrht         FLOAT      NULL,
        earthht        FLOAT      NULL,
        tvazim         FLOAT      NULL,
        evazim         FLOAT      NULL,
        tvelev         FLOAT      NULL,
        evelev         FLOAT      NULL,
        tvdistes       FLOAT      NULL,
        tvdisttu       FLOAT      NULL,
        evdistes       FLOAT      NULL,
        evdisttu       FLOAT      NULL,
        angleutv       FLOAT      NULL,
        anglesev       FLOAT      NULL,
        tsoffaxis      CHAR(1)    NULL,
        tstrueaz       FLOAT      NULL,
        tstrueel       FLOAT      NULL,
        angleute       FLOAT      NULL,
        angleuta       FLOAT      NULL,
        angleeta       FLOAT      NULL,
        angleatv       FLOAT      NULL,
        adisc_atv      FLOAT      NULL,
        terragain      FLOAT      NULL,
        terramodel     CHAR(15)   NULL,
        terraxref      CHAR(12)   NULL,
        earthagain     FLOAT      NULL,
        earthamodel    CHAR(15)   NULL,
        earthaxref     CHAR(12)   NULL,
        processed      INT        NULL,
        CONSTRAINT PK_tsip_arc_te_ante PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_te_ante_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_te_ante_run ON web.tsip_arc_te_ante (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_te_chan', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_te_chan (
        arc_id         BIGINT     IDENTITY(1,1) NOT NULL,
        run_id         BIGINT     NOT NULL,
        interferer     CHAR(1)    NULL,
        terrcall1      CHAR(9)    NULL,
        terrcall2      CHAR(9)    NULL,
        terrbndcde     CHAR(4)    NULL,
        terranum       SMALLINT   NULL,
        terrchid       CHAR(4)    NULL,
        earthlocation  CHAR(10)   NULL,
        earthcall1     CHAR(9)    NULL,
        earthchid      CHAR(4)    NULL,
        inttraftx      CHAR(6)    NULL,
        victrafrx      CHAR(6)    NULL,
        inteqpttx      CHAR(8)    NULL,
        viceqptrx      CHAR(8)    NULL,
        intfreqtx      FLOAT      NULL,
        inttxpwr       FLOAT      NULL,
        inttxpwr2      FLOAT      NULL,
        inttxafls      FLOAT      NULL,
        inttxafls2     FLOAT      NULL,
        vicrxafls      FLOAT      NULL,
        vicfreqrx      FLOAT      NULL,
        vicpwrrx       FLOAT      NULL,
        stattx         CHAR(1)    NULL,
        statrx         CHAR(1)    NULL,
        energy         FLOAT      NULL,
        etreport       SMALLINT   NULL,
        tereport       SMALLINT   NULL,
        ctxinttraftx   CHAR(6)    NULL,
        ctxvictrafrx   CHAR(6)    NULL,
        ctxeqpt        CHAR(8)    NULL,
        calctype       CHAR(3)    NULL,
        earthmdsc      FLOAT      NULL,
        terrmdsc       FLOAT      NULL,
        eartheirp      FLOAT      NULL,
        terreirp       FLOAT      NULL,
        freqsep        FLOAT      NULL,
        scang          FLOAT      NULL,
        loss20mode1    FLOAT      NULL,
        calci20mode1   FLOAT      NULL,
        loss01mode1    FLOAT      NULL,
        calci01mode1   FLOAT      NULL,
        loss01mode2    FLOAT      NULL,
        calci01mode2   FLOAT      NULL,
        reqd20mode1    FLOAT      NULL,
        reqd01mode1    FLOAT      NULL,
        reqd01mode2    FLOAT      NULL,
        marg20mode1    FLOAT      NULL,
        marg01mode1    FLOAT      NULL,
        marg01mode2    FLOAT      NULL,
        remterracode   CHAR(12)   NULL,
        remterragain   FLOAT      NULL,
        processed      INT        NULL,
        terrant        SMALLINT   NULL,
        CONSTRAINT PK_tsip_arc_te_chan PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_te_chan_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_te_chan_run ON web.tsip_arc_te_chan (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_te_parm', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_te_parm (
        arc_id      BIGINT     IDENTITY(1,1) NOT NULL,
        run_id      BIGINT     NOT NULL,
        protype     CHAR(1)    NULL,
        envtype     CHAR(8)    NULL,
        proname     CHAR(16)   NULL,
        envname     CHAR(16)   NULL,
        tsorbout    CHAR(1)    NULL,
        spherecalc  CHAR(1)    NULL,
        fsep        FLOAT      NULL,
        coordist    FLOAT      NULL,
        analopt     CHAR(4)    NULL,
        margin      FLOAT      NULL,
        numchan     SMALLINT   NULL,
        chancodes   CHAR(19)   NULL,
        tempant     CHAR(15)   NULL,
        tempctx     CHAR(15)   NULL,
        tempplan    CHAR(15)   NULL,
        tempequip   CHAR(15)   NULL,
        country     CHAR(3)    NULL,
        selsites    CHAR(15)   NULL,
        numcodes    SMALLINT   NULL,
        codes       CHAR(164)  NULL,
        runname     CHAR(5)    NULL,
        reports     INT        NULL,
        numcases    INT        NULL,
        numtecases  INT        NULL,
        parmparm    CHAR(50)   NULL,
        mdate       CHAR(10)   NULL,
        mtime       CHAR(8)    NULL,
        CONSTRAINT PK_tsip_arc_te_parm PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_te_parm_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_te_parm_run ON web.tsip_arc_te_parm (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_ts_statsum', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_ts_statsum (
        arc_id     BIGINT      IDENTITY(1,1) NOT NULL,
        run_id     BIGINT      NOT NULL,
        tmpinter   VARCHAR(1)  NULL,
        tmpcall1   VARCHAR(10) NULL,
        tmpname    VARCHAR(32) NULL,
        tmpoper    VARCHAR(6)  NULL,
        tmplatit   INT         NULL,
        tmplongit  INT         NULL,
        tmpgrnd    FLOAT       NULL,
        CONSTRAINT PK_tsip_arc_ts_statsum PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_ts_statsum_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE
    );
    CREATE INDEX IX_tsip_arc_ts_statsum_run ON web.tsip_arc_ts_statsum (run_id);
END;

IF OBJECT_ID(N'web.tsip_arc_te_statsum', N'U') IS NULL
BEGIN
    CREATE TABLE web.tsip_arc_te_statsum (
        arc_id      BIGINT      IDENTITY(1,1) NOT NULL,
        run_id      BIGINT      NOT NULL,
        statsum_part CHAR(1)    NOT NULL,
        tmpinter    VARCHAR(1)  NULL,
        tmplocat    VARCHAR(11) NULL,
        tmpcall1    VARCHAR(10) NULL,
        tmpname     VARCHAR(32) NULL,
        tmpoper     VARCHAR(6)  NULL,
        tmplatit    INT         NULL,
        tmplongit   INT         NULL,
        tmpgrnd     FLOAT       NULL,
        CONSTRAINT PK_tsip_arc_te_statsum PRIMARY KEY CLUSTERED (arc_id),
        CONSTRAINT FK_tsip_arc_te_statsum_run FOREIGN KEY (run_id)
            REFERENCES web.tsip_run (run_id) ON DELETE CASCADE,
        CONSTRAINT CK_tsip_arc_te_statsum_part CHECK (statsum_part IN ('P', 'E'))
    );
    CREATE INDEX IX_tsip_arc_te_statsum_run ON web.tsip_arc_te_statsum (run_id);
END;
